

cc_library(
  name = "tls",
  srcs = ["src/tls_syntax.cpp"],
  hdrs = [
    "include/tls/tls_syntax.h",
    "include/tls/compat.h",
  ],
  strip_include_prefix = "include",
  visibility = ["//visibility:public"],
)
