

cc_library(
  name = "bytes",
  srcs = ["src/bytes.cpp"],
  hdrs = [
    "include/bytes/bytes.h",
    "include/tls/compat.h",
    "include/tls/tls_syntax.h",
  ],
  strip_include_prefix = "include",
  visibility = ["//visibility:public"],
)
